name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build solution
        working-directory: Financio/Financio
        run: |
          dotnet restore
          dotnet build
          
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        projectBaseDir: Financio/Financio
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  unit-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Run unit tests
        working-directory: Financio/UnitTestProject
        run: |
          dotnet restore
          dotnet test --filter FullyQualifiedName~UnitTestProject

  integration-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Run integration tests
        working-directory: Financio/IntegrationTestProject
        run: |
          dotnet restore
          dotnet test --filter FullyQualifiedName~IntegrationTestProject
          
  build-and-push-image:
    needs: [unit-test, integration-test]
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: btymo
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        working-directory: Financio
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker build -t btymo/btymo-repo:backend .
          docker push btymo/btymo-repo:backend
